### PR TITLE
feature: Implemented basic UI with screen navigation

### PR DESCRIPTION
**Pull request by neliudochka**
**UI.**
- used XML files
- implemented needed structure with 4 screens (screenshots below)
- for now, in photo containers, there are shrek pictures

__ENcode screens:_
    Setup_
image

   _Result_
image

_DEcode screens:
  Setup_
image

  _Result_
image

**Navigation**.
- Navigation made with navigation component.
- Fragments as destination points.
- Implemented bottom navigation bar.

### CODE REVIEW

**Review by AKushch1337 — CHANGES_REQUESTED** [review]
- Bad structuring of files: separate fragment files into different directories
- Questionable logic of UI: you may want to add back buttons in result screens, UX will be improved
- Found a bug: bottom navigation bar buttons highlighting doesn't always function correctly. It seems to me there's a problem with Result fragments. 
- Maybe add some info about which screen the user is currently using

**Comment by neliudochka** [comment]
- Changed project structure.
Code files:
Now, fragments are in a different directory. Inside it, they are also divided into two directories: encode (for the encode setup and result fragments), and decode (for the decode setup and result fragments).

XML layout files:
Placed layout files in subfolders. Layout files are now in the layouts directory. Structure:
├── layouts
│   ├── decode
│   │   └── layout
│   │   	├── fragment_decode_result.xml
│   │   	└── fragment_decode_setup.xml
│   ├── encode
│   │   └── layout
│   │   	├── fragment_encode_result.xml
│   │   	└── fragment_encode_setup.xml
│   └── mainActivity
│   	└── layout
│       	└── activity_main.xml

The article I used: https://medium.com/mindorks/how-to-put-android-layout-files-in-subfolders-1f7cf07ff48f

- Deleted unused imports
- 
- The toolbar title show which fragment user currently using
- 
- fixed Bottom Navigation Bar bug.
I didn’t find a solution for this bug, so I changed setupWithNavController() with my own implementation of Bottom Navigation Bar navigation.

- Replaced LinearLayout in layout files with ConstraintLayout
This gives better flexibility - the design will look better on screens with different measurements.

- In result layouts added back buttons

- Extracted hardcoded text to variables

Screenshots:
image
image
image
image

**Review by AKushch1337 — CHANGES_REQUESTED** [review]
Everything is ok, but you forgot to put listeners to the "to setup" buttons. Add them, please

**Comment by neliudochka** [comment]
- Added listeners to "toSetup" bottoms

**Review by AKushch1337 — APPROVED** [review]
All good! Nice work

**Comment by neliudochka** [comment]
image

**Comment by AKushch1337** [comment]
> image

https://www.youtube.com/watch?v=aCrXAf3eek8&ab_channel=Machinepriest

**Pull request merged**
