### PR TITLE
Feature: pass data

### PR DESCRIPTION
**Pull request by neliudochka**
- added the ability to pass data between fragments with Safe Args
Info about Safe args here: https://developer.android.com/guide/navigation/use-graph/pass-data
I pass the message as a string, and image Uri as a string from the Setup fragment to the Result fragment.
If you haven't added text or image, then you'll see a Toast message telling you this.

- Added SafeArgs to the readme technologies section

- Deleted 2 default photos.
The population of Sherks is decreasing drastically. Only 2 left...

**Screenshots!**

***Encode section:***
- Setup
Taking a picture
 

Trying to press Start, but receiving a Toast message
 

Entering a message
 

- Result

***Decode section:***
- Setup

- Result

### CODE REVIEW

**Review by AKushch1337 — APPROVED** [review]
Nice clean code. Fancy sketch of IM-23 group logo. Glad to see less of Shrek, of course. Can't see any problems with the code though, you're amazing and talented😺

**Comment by neliudochka** [comment]
You forgot "she's got a point, she's an icon, she's a legend and she is the moment"

**Comment by AKushch1337** [comment]
> You forgot "she's got a point, she's an icon, she's a legend and she is the moment"

I'm sorry 😿.

**Comment by neliudochka** [comment]
image

**Pull request merged**
